FROM gsoci.azurecr.io/giantswarm/klaus-debian:0.0.27
USER root
RUN apt-get update && apt-get install -y --no-install-recommends git python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*
USER klaus
