FROM gsoci.azurecr.io/giantswarm/klaus-debian:0.0.28
USER root
RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*
LABEL io.giantswarm.klaus.type=toolchain \
      io.giantswarm.klaus.name=git
USER klaus
