ARG KLAUS_VERSION=0.0.20
FROM gsoci.azurecr.io/giantswarm/klaus-debian:${KLAUS_VERSION}
USER root
RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*
USER klaus
